// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGGT76vqjCloaQzwXLDIycnbC1o4dY4Lk',
    appId: '1:615059940030:web:9c91f2ec301c8b516c34ef',
    messagingSenderId: '615059940030',
    projectId: 'amdbuygulama',
    authDomain: 'amdbuygulama.firebaseapp.com',
    storageBucket: 'amdbuygulama.appspot.com',
    measurementId: 'G-QGJ57FL388',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUl26_xGS9TLJzUvsV6kXwv5sJI3Eos9g',
    appId: '1:615059940030:android:7216d858736f9a556c34ef',
    messagingSenderId: '615059940030',
    projectId: 'amdbuygulama',
    storageBucket: 'amdbuygulama.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUTONHsW8_7G3x1QaZa1gUNsUF5hoORf4',
    appId: '1:615059940030:ios:c9fcc35605b948f66c34ef',
    messagingSenderId: '615059940030',
    projectId: 'amdbuygulama',
    storageBucket: 'amdbuygulama.appspot.com',
    iosClientId: '615059940030-68nnpuhmbeqvlp7v8tvje3b77a59vvmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.amdb',
  );
}
